Hn debug

diff --git a/tests/hn/manticoresearch/pre_hook b/tests/hn/manticoresearch/pre_hook
--- a/tests/hn/manticoresearch/pre_hook
+++ b/tests/hn/manticoresearch/pre_hook
@@ -12,4 +12,10 @@ php manticoresearch/generate_manticore_config.php --test=$test --type=$suffix > 
 mkdir -p manticoresearch/idx$suffix/data/binlog
 chmod 777 manticoresearch/idx$suffix/data/binlog
 suffix=$suffix docker-compose -f ../../docker-compose.yml --env-file ../../.env up -d manticoresearch
-while ! nc -z localhost 9308; do sleep 1; done
+
+if timeout 60 grep -qm1 'accepting connections' <(docker logs -f manticoresearch_engine); then
+  echo 'Accepting connections';
+else
+  echo 'Manticore failed to start properly in 60 seconds';
+  exit 1
+fi
