Return csv support in logs10m

diff --git a/tests/logs10m/quickwit/pre_hook b/tests/logs10m/quickwit/pre_hook
--- a/tests/logs10m/quickwit/pre_hook
+++ b/tests/logs10m/quickwit/pre_hook
@@ -27,10 +27,9 @@ curl -s -XPOST "${HOST}/api/v1/indexes" \
   --data-binary @./quickwit/index-config.yaml
 
 rm -f ./data/data_splitted.*
-quickwit_jsonl=./data/data.quickwit.jsonl
-echo -e "\tConvert CSV to JSONL. The current operation might take time. You can check progress by 'cat ${quickwit_jsonl} | wc -l'"
-php ./quickwit/csv_jsonl.php ./data/data.csv "$quickwit_jsonl"
-echo -e "\tEnd converting"
+if [ ! -f data/data.jsonl ]; then
+    echo -e "\tMissing data/data.jsonl; run ./prepare_jsonl/prepare.sh first"
+    exit 1
+fi
 
-split -l 10000 -a 5 "$quickwit_jsonl" ./data/data_splitted.
-rm "$quickwit_jsonl"
+split -l 10000 -a 5 ./data/data.jsonl ./data/data_splitted.
