Taxi sketches

diff --git a/tests/hn_small/manticoresearch/post_hook b/tests/hn_small/manticoresearch/post_hook
--- a/tests/hn_small/manticoresearch/post_hook
+++ b/tests/hn_small/manticoresearch/post_hook
@@ -4,8 +4,14 @@ echo -en "\tFinished loading to index at "
 date
 
 suffix=$suffix docker-compose -f ../../docker-compose.yml --env-file ../../.env restart manticoresearch
-while ! nc -z localhost 9308; do sleep 1; done
-sleep 5
+
+if timeout 60 grep -qm1 '\[BUDDY\] started' <(docker logs -f manticoresearch_engine); then
+  echo 'Accepting connections';
+else
+  echo 'Manticore failed to start properly in 60 seconds';
+  exit 1
+fi
+
 inserted=$(docker exec manticoresearch_engine mysql -h0 -P9306 -e "SELECT count(*) FROM $test\G" | grep count | cut -d" " -f2)
 echo -e "\tCount of inserted documents: $inserted"
 
