Hn sketches

diff --git a/tests/hn_small/init b/tests/hn_small/init
--- a/tests/hn_small/init
+++ b/tests/hn_small/init
@@ -1,1 +1,34 @@
-. ../hn/init
+#!/usr/bin/env bash
+trap 'jobs -p | xargs -r kill' EXIT
+
+current_dir=$(basename "$PWD")
+test_dir=$(realpath "$(dirname "$0")")
+cd "$test_dir"
+
+export test="$current_dir"
+
+COLORED='\033[0;33m'
+NC='\033[0m' # No Color
+
+docker-compose -f ../../docker-compose.yml --env-file ../../.env down
+docker-compose -f ../../docker-compose.yml --env-file ../../.env rm -fs
+
+echo -e "${COLORED}Preparing CSV:${NC}"
+./prepare_csv/prepare.sh | while IFS= read -r line; do echo -e "\t$line"; done
+if [ $? -ne 0 ]; then
+  echo -e "\tCouldn't prepare CSV"
+  exit 1
+fi
+
+../../init --engine=clickhouse
+../../init --engine=elasticsearch
+../../init --engine=manticoresearch --type=rowwise
+../../init --engine=meilisearch
+../../init --engine=mysql
+../../init --engine=postgres
+../../init --engine=typesense
+
+# MySQL Percona
+if [[ -d mysql_percona ]]; then
+  ../../init --engine=mysql_percona
+fi
