Typesence init

diff --git a/tests/hn_small/typesense/init b/tests/hn_small/typesense/init
--- a/tests/hn_small/typesense/init
+++ b/tests/hn_small/typesense/init
@@ -1,44 +1,42 @@
 #!/usr/bin/env bash
 
+cmd="test=$test suffix=$suffix docker-compose -f ../../docker-compose.yml --env-file ../../.env up -d typesense"
+echo -e "\tStarting mysql percona ($cmd)"
+eval "$cmd"
 
-    cmd="test=$test suffix=$suffix docker-compose -f ../../docker-compose.yml --env-file ../../.env up -d typesense"
-    echo -e "\tStarting mysql percona ($cmd)"
-    eval "$cmd"
+# WAIT UNTIL TYPESENCE BECAME AVAILABLE
 
+temp_log_file=$(mktemp)
+timeout 60 docker logs -f typesense_engine >"$temp_log_file" 2>&1 &
+log_pid=$!
 
-    # WAIT UNTIL TYPESENCE BECAME AVAILABLE
+while true; do
+  if grep 'Peer refresh succeeded' "$temp_log_file"; then
+    echo 'accepting connections'
+    kill $log_pid 2>/dev/null
+    rm "$temp_log_file"
+    break
+  fi
 
-    temp_log_file=$(mktemp)
-    timeout 60 docker logs -f typesense_engine > "$temp_log_file" 2>&1 &
-    log_pid=$!
+  if ! kill -0 $log_pid 2>/dev/null; then
+    echo 'Timeout failed'
+    rm "$temp_log_file"
+    exit 1
+  fi
 
-    while true; do
-      if grep 'Peer refresh succeeded' "$temp_log_file"; then
-        echo 'accepting connections'
-        kill $log_pid 2>/dev/null
-        rm "$temp_log_file"
-        break;
-      fi
+  sleep 1
+done
 
-      if ! kill -0 $log_pid 2>/dev/null; then
-        echo 'Timeout failed'
-        rm "$temp_log_file"
-        exit 1
-      fi
+export TYPESENSE_API_KEY='manticore'
+export TYPESENSE_HOST='http://localhost:8108'
 
-      sleep 1
-    done
+if curl -v --silent ${TYPESENSE_HOST}/collections/${test} \
+  -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" 2>&1 | grep "Not Found"; then
 
-    export TYPESENSE_API_KEY='manticore'
-    export TYPESENSE_HOST='http://localhost:8108'
-
-    if curl -v --silent ${TYPESENSE_HOST}/collections/${test} \
-    -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" 2>&1 | grep "Not Found"; then
-
-      curl "${TYPESENSE_HOST}/collections" \
-                  -X POST \
-                  -H "Content-Type: application/json" \
-                  -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d "{
+  curl "${TYPESENSE_HOST}/collections" \
+    -X POST \
+    -H "Content-Type: application/json" \
+    -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d "{
                     \"name\": \"${test}\",
                     \"fields\": [
                       {\"name\": \"id\", \"type\": \"int64\" },
@@ -55,31 +53,32 @@
                     \"default_sorting_field\": \"story_id\"
                   }"
 
-        if [ ! -f data/data.jsonl ]; then
-          php ./typesense/csv_jsonl.php ./data/data.csv ./data/data.jsonl
+  if [ ! -f data/data.jsonl ]; then
+    php ./typesense/csv_jsonl.php ./data/data.csv ./data/data.jsonl
 
-          echo -en "\tStarting loading at "; date
+    echo -en "\tStarting loading at "
+    date
 
-          curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -X POST \
-          --data-binary @./data/data.jsonl \
-          "${TYPESENSE_HOST}/collections/${test}/documents/import?batch_size=100" | head -n 10
-          echo -en "\tFinished loading to index at "; date
-          rm data/data.jsonl
-        fi
+    curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -X POST \
+      --data-binary @./data/data.jsonl \
+      "${TYPESENSE_HOST}/collections/${test}/documents/import?batch_size=100" | head -n 10
+    echo -en "\tFinished loading to index at "
+    date
+    rm data/data.jsonl
+  fi
 
-sleep 5
-echo -en "\tWait until Typesence process batch";
-  for i in `seq 1 120`; do
+  sleep 5
+  echo -en "\tWait until Typesence process batch"
+  for i in $(seq 1 120); do
     if curl -I -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
-             -X GET "${TYPESENSE_HOST}/collections/${test}" 2>&1 | grep "HTTP/1.1 200 OK"; then
-        break
+      -X GET "${TYPESENSE_HOST}/collections/${test}" 2>&1 | grep "HTTP/1.1 200 OK"; then
+      break
     fi
     printf '%s' "."
     sleep 1
   done
-  echo -en "\tFinished";
+  echo -en "\tFinished"
 
-      else
-        echo -e "\tNo need to rebuild"
-    fi
-
+else
+  echo -e "\tNo need to rebuild"
+fi
